package edu.upenn.cis.orchestra.repository.model.beans;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.BeanUtils;

public class ScForeignKeyBean extends ScConstraintBean 
{
	/** Referenced relation is stored as a String because IBATIS does 
	 * not deal with circular dependencies yet.
	 * Moreover we might be able to use the beans instead of the Model
	 * objects for web services in order to reduce the complexity 
	 * of the XML files generated by java-ws
	 */ 
	protected String _refRelation;
	
	/**
	 * Referenced fields names, stored as string for the same reason.
	 */
	protected List<String> _refFields = new ArrayList<String> ();
	
	
	public ScForeignKeyBean ()
	{		
		super ();
	}

	/**
	 * Had to create this method to allow copy of beans with same properties than our model beans, because 
	 * JaxB does not allow to replace the generated beans for client applications by our own beans. Event though they
	 * will have exactly the same getters and settes
	 * @param beanSameProperties Bean to copy in our standard beans
	 */	
	public ScForeignKeyBean (Object beanSameProperties)
	{
		super ();
		// Can use BeanUtils.copyproperties because ScConstraintBean does not contain any 
		// complex object. But this is not really clean
		BeanUtils.copyProperties(beanSameProperties, this);
	}

	public List<String> getRefFields() {
		return _refFields;
	}


	public void setRefFields(List<String>fields) {
		if (fields != null)
			_refFields = fields;
	}


	public String getRefRelation() {
		return _refRelation;
	}


	public void setRefRelation(String relation) {
		_refRelation = relation;
	}
	
	
	
	
	

}
