package edu.upenn.cis.orchestra.datamodel;


public class IntPeerID extends AbstractPeerID {
	private static final long serialVersionUID = 1L;

	static final byte typeId = 1;
	static final String typeName = "INTEGER";
	
	public IntPeerID() {
		_id = -1;
	}
	
	public IntPeerID(int value) {
		_id = value;
	}
	
	public int getID() {
		return _id;
	}
	
	public int hashCode() {
		return _id;
	}
	
	public boolean equals(Object o) {
		if (o == null || o.getClass() != this.getClass())
			return false;
		IntPeerID ipi = (IntPeerID) o;
		return (_id == ipi._id);
	}
	
	public int compareTo(AbstractPeerID o) {
		if (!(o instanceof IntPeerID)) {
			return typeId - getIdForClass(o.getClass());
		}

		IntPeerID ipi = (IntPeerID) o;
		if (_id < ipi._id)
			return -1;
		else if (_id > ipi._id)
			return 1;
		else
			return 0;
	}
	
	public String toString() {
		return "@" + _id;
	}
	
	public IntPeerID duplicate() {
		// Safe since IntPeerID is immutable
		return this;
	}
	
	private final int _id;

	@Override
	protected byte[] getSubclassBytes() {
		return IntType.getBytes(_id);
	}

	/**
	 * Decode the ID from a byte array generated by a class to getSubclassBytes
	 * 
	 * @param bytes		The data to read from
	 * @param offset	The start of the data for the ID
	 * @param length	The length of the data for the ID
	 * @return			The object encoding the ID
	 */
	protected static AbstractPeerID fromSubclassBytes(byte[] bytes, int offset, int length) {
		return new IntPeerID(IntType.getValFromBytes(bytes, offset));
	}
	
	protected static AbstractPeerID fromStringRep(String rep) {
		return new IntPeerID(Integer.parseInt(rep));
	}

	@Override
	protected String getSubclassString() {
		return Integer.toString(_id);
	}
}