CREATE FUNCTION Skolem.skolemStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStr!skolemStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStr!skolemStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStr!skolemStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStr!skolemStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStr!skolemStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStr!skolemStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128),
	StrVal13 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128),
	StrVal13 VARCHAR(128),
	StrVal14 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128),
	StrVal13 VARCHAR(128),
	StrVal14 VARCHAR(128),
	StrVal15 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128),
	StrVal13 VARCHAR(128),
	StrVal14 VARCHAR(128),
	StrVal15 VARCHAR(128),
	StrVal16 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128),
	StrVal13 VARCHAR(128),
	StrVal14 VARCHAR(128),
	StrVal15 VARCHAR(128),
	StrVal16 VARCHAR(128),
	StrVal17 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128),
	StrVal13 VARCHAR(128),
	StrVal14 VARCHAR(128),
	StrVal15 VARCHAR(128),
	StrVal16 VARCHAR(128),
	StrVal17 VARCHAR(128),
	StrVal18 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

CREATE FUNCTION Skolem.skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr (
	Func VARCHAR(10),
	StrVal0 VARCHAR(128),
	StrVal1 VARCHAR(128),
	StrVal2 VARCHAR(128),
	StrVal3 VARCHAR(128),
	StrVal4 VARCHAR(128),
	StrVal5 VARCHAR(128),
	StrVal6 VARCHAR(128),
	StrVal7 VARCHAR(128),
	StrVal8 VARCHAR(128),
	StrVal9 VARCHAR(128),
	StrVal10 VARCHAR(128),
	StrVal11 VARCHAR(128),
	StrVal12 VARCHAR(128),
	StrVal13 VARCHAR(128),
	StrVal14 VARCHAR(128),
	StrVal15 VARCHAR(128),
	StrVal16 VARCHAR(128),
	StrVal17 VARCHAR(128),
	StrVal18 VARCHAR(128),
	StrVal19 VARCHAR(128) )
RETURNS INTEGER
LANGUAGE JAVA
DISALLOW PARALLEL
EXTERNAL ACTION
NOT DETERMINISTIC
FENCED NOT THREADSAFE
EXTERNAL NAME 'SkolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr!skolemStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStrStr'
PARAMETER STYLE JAVA ;

